version: '3.1'

services:
  springboot:
    image: vuppalar/springboot:abcde
    ports:
      - 8080:8080
    networks:
    - springappnetwork
  mongo:
    image: mongo
    ports:
       - 9090:8080
    volumes:
      - mongodb:/data/db
    networks:
    - springappnetwork
    
volumes:
  mongodb:
    
networks:
  springappnetwork:
    
