version: '3.1'

services:
  springboot:
    image: vuppalar/springboot:$IMAGEVERSION
    ports:
      - 8080:8080
    networks:
    - springappnetwork
  mongo:
    image: mongo
    volumes:
      - mongodb:/data/db
    networks:
    - springappnetwork
    
volumes:
  mongodb:
    
networks:
  springappnetwork:
    
